JDP200302-24 OrderController methods
interceptor2048/JDP-2003-02 pull request #15
Opened 2020-04-13 19:37 UTC by dawid-walter

2020-04-14 06:44 UTC, SirVertar commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +
Wiem, że to żaden błąd i może tak zostać, ale nie powinniśmy trzymać się jednej koncepcji wstrzykiwania zależności? Bo wcześniej robiliśmy chyba przez pola  klasy ?

2020-04-14 06:44 UTC, SirVertar commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private List<Product> productsList;
Pytanie czy chcemy żeby JSON Order miał listę produktów? Sam o tym na ten moment nie wiem :)

2020-04-14 07:11 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private List<Product> productsList;
Jakos musimy wiedziec i wyswietlic co ktos zamowil :)

2020-04-15 09:09 UTC, SirVertar submitted a review, later dismissed

2020-04-15 09:53 UTC, interceptor2048 requested changes

2020-04-15 09:53 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private List<Product> productsList;
Tu nie może być listy produktów. Jak już to lista `ProductDto`

2020-04-15 10:00 UTC, NaliKod reviewed
W OrderMapper OrderDTo i Order brakuje mi mapowania listy produktów (getProdcuct) na poszczególne ProductDTo i Prodcuct po stream:
poniżej skopiowałam kod w kórym i bym to uwzględniła.

 public Order mapToOrder(final OrderDto orderDto) {
        return new Order(orderDto.getId(), orderDto.getCreationDate(), orderDto.getStatus(), orderDto.getUser(), orderDto.getProductsList());
    }

    public OrderDto mapToOrderDto(final Order order) {
        return new OrderDto(order.getId(), order.getCreationDate(), order.getStatus(),order.getUser(), order.getProducts());
    }

2020-04-15 11:27 UTC, interceptor2048 requested changes

2020-04-15 11:27 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private Group group;
Po co group skoro jest `groupId`?

2020-04-15 12:26 UTC, interceptor2048 requested changes

2020-04-15 12:26 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +    public ProductMapper(OrderMapper orderMapper, GroupRepository groupRepository) {
Używaj serwisów zamiast repository

2020-04-16 12:03 UTC, NaliKod reviewed
Cześć Dawid
Chciałam dopytać o metody mapToProductDtoList, mapToProductList zuważyła, że używasz builder i nie wpisujesz wszystki parametrów przy mapowaniu dotyczących Order i Cart. Zastanawiam się co się stanie z tą infomacją czy zostanie ustawiona na 0 , co wydaje mi się nie prawidłowe ?

2020-04-16 12:06 UTC, NaliKod commented
Jak wygląda ProductDto ?,
 klasy wygląda tak :
public class ProductDto {
    private Long id;
    private String name;
    private String description;
    private BigDecimal price;
    private Long groupId;
    private List<Long>ordersId;
    private List<Long>cartsId;
}

Czy zupełnie zrezygnowałeś z prametrów 2 ostatnich ?

2020-04-16 12:11 UTC, NaliKod reviewed
Dawid już znalazłam odpowiedź na czacie.

2020-04-16 12:20 UTC, NaliKod approved these changes

2020-04-16 12:24 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +    public ProductMapper(OrderMapper orderMapper, GroupRepository groupRepository) {
Poprawione w dalszych comitach

2020-04-16 13:48 UTC, interceptor2048 approved these changes

2020-04-16 14:30 UTC, merged